# Generated by Django 3.0.3 on 2021-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20210603_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll',
            field=models.CharField(max_length=50),
        ),
    ]
